version: '3.8'

services:
  web:
    build: .
    container_name: purchase-agent-web
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=purchase_agent.settings.production      
      - POSTGRES_DB=purchase_agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: purchase-agent-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=purchase_agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: