version: '3.8'

services:
  web:
    build: .
    container_name: purchase-agent-website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: purchase-agent-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: purchase_agent

volumes:
  postgres_data:


